sudo: false
language: node_js

node_js:
  - "4.0.0"
  - "5.0.0"
  - "6.0.0"
  - "7.0.0"
  - "node"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install
  - npm run build

script:
  - npm run benchmark
  - npm run spec

cache:
  directories:
    - node_modules
